BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS         += "qti-display"
BBFILE_PRIORITY_qti-display = "12"
BBFILE_PATTERN_qti-display := "^${LAYERDIR}/"

LAYERSERIES_COMPAT_qti-display = "kirkstone"

BBFILES += "${LAYERDIR}/recipes/*/*.bb \
            ${LAYERDIR}/recipes/*/*.bbappend"
