#!/bin/sh
########################################################################
#Copyright (c) 2017, The Linux Foundation. All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted provided that the following conditions are
#met:
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials provided
#      with the distribution.
#    * Neither the name of The Linux Foundation nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
#WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
#ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
#BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
#OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
#IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#########################################################################

### BEGIN INIT INFO
# Provides: weston
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

if test -e /etc/default/weston ; then
        . /etc/default/weston
fi

killproc() {
        pid=`/bin/pidof $1`
        [ "$pid" != "" ] && kill $pid
}

read CMDLINE < /proc/cmdline
for x in $CMDLINE; do
        case $x in
        weston=false)
        echo "Weston disabled"
        exit 0;
                ;;
        esac
done

case "$1" in
  start)
        . /etc/profile

        # This is all a nasty hack
        if test -z "$XDG_RUNTIME_DIR"; then
                export XDG_RUNTIME_DIR=/run/user/0
                mkdir --parents $XDG_RUNTIME_DIR
                chmod 0700 $XDG_RUNTIME_DIR
        fi

	if [ ! -e "/usr/libexec/weston.ini" ];then
		echo "Desktop=default" >> /usr/libexec/weston.ini
		echo "Interface=DSI" >> /usr/libexec/weston.ini
	fi

	if [ -e "/sys/class/backlight/panel0-backlight/brightness" ];then
		echo "127" > /sys/class/backlight/panel0-backlight/brightness
	fi

	Interface_type=`cat /usr/libexec/weston.ini | grep Interface | cut -d "=" -f2`
	if [ "$Interface_type" = "DP" ];then
		while ((1))
		do
			DP_STATUS=`cat /sys/devices/platform/soc/ae00000.qcom,mdss_mdp/drm/card0/card0-DP-1/status`
			if [ "$DP_STATUS" = "connected" ];then
				break
			fi
			sleep 1
		done
	elif [ "$Interface_type" = "DSI" ];then
		echo "Set interface for DSI" >> /tmp/weston.log
	else
		echo "Please set the Interface as DSI or DP in /usr/libexec/weston.ini" >> /tmp/weston.log
		echo "After set, please restart service init_display (systemctl restart init_display) or reboot" >> /tmp/weston.log
		exit 1
	fi

	echo "WESTON INITIALIZATION STARTUP"
	Desktop=`cat /usr/libexec/weston.ini | grep Desktop | cut -d "=" -f2`
	Connector_id=`cat /sys/kernel/debug/dri/0/state | grep $Interface_type | cut -d "[" -f2 | cut -d "]" -f1`
	if [ "$Desktop" = "maynard" ];then
		openvt -s weston -- $OPTARGS --connector=$Connector_id  --config=/usr/libexec/weston.ini --idle-time=4294967 --log=/tmp/weston.log
	elif [ "$Desktop" = "default" ];then
		echo "Set Desktop to default: Weston" >> /tmp/weston.log
		openvt -s weston -- $OPTARGS --connector=$Connector_id --idle-time=4294967 --log=/tmp/weston.log
	else
		echo "Please set the Desktop as default or maynard in /usr/libexec/weston.ini" >> /tmp/weston.log
		echo "After set, please restart service init_display (systemctl restart init_display) or reboot" >> /tmp/weston.log
		exit 1
	fi
  ;;

  stop)
        echo "Stopping Weston"
        killproc weston
  ;;

  restart)
    $0 stop
        sleep 1
        $0 start
  ;;

  *)
        echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
