# configuration file for Weston
[core]
idle-time=0
repaint-window=10
require-outputs=none

[output]
name=DSI-1
mode=on

[output]
name=DP-1
mode=on

[output]
name=Virtual-1
mode=off

[output]
name=Virtual-2
mode=off

[shell]
clock-format=seconds
